#!/usr/bin/env python3
"""Precompute the hydrodynamic peak load-factor coefficient Clf(kappa).

Source: NACA TN 1516 (Milwitzky, 1948), "A generalized theoretical and
experimental investigation of the motions and hydrodynamic loads experienced by
V-bottom seaplanes during step-landing impacts" (documentation/19930082553.pdf).

Clf is the *load-factor* coefficient C_l (subscript l = load) from the paper --
it maps the contact state to the peak CG load factor via
    n_peak = Clf(kappa) * ydot0^2 * (alpha_hull / (W g^2))^(1/3).
It is NOT the aerodynamic max-lift coefficient CLmax used by the descent barrier.

For each approach parameter kappa, the velocity ratio u = ydot/ydot0 at maximum
acceleration is the root of the transcendental eq (27); Clf then follows from
eq (25). Neither has a closed form (eqs 26/27 are transcendental), so we solve
offline and emit a constexpr table that the C++ barrier interpolates at run time.

Anchor (eqs 39/40): at kappa=0, u=7/9 and Clf=0.6123.

Usage:
    python3 scripts/precompute_impact_clf.py            # regenerate the header
    python3 scripts/precompute_impact_clf.py --check     # verify only, no write
"""
import math
import os
import sys

# Practical range of the approach parameter (NACA TN 1516, p.15); the runtime
# barrier clamps kappa to this range, so the table spans exactly it.
KAPPA_MIN, KAPPA_MAX = 0.2, 10.0
N_POINTS = 81           # log-spaced grid; linear-in-kappa interp between points
ANCHOR_CLF = 0.6123     # Clf(0), eq 40
HEADER = os.path.join(os.path.dirname(__file__), os.pardir,
                      "include", "autoland", "impact_clf_table.hpp")


def eq27_residual(u, k):
    """F(u;kappa) = 0 at the velocity ratio of maximum acceleration (eq 27)."""
    return (math.log((9 * u + 6 * k) * (u + k) / ((7 * u + 6 * k) * (1 + k)))
            - k * (1.0 / (1 + k) - 1.0 / (u + k)))


def velocity_ratio(k):
    """Solve eq (27) for u in (0,1). F(0+) < 0, F(1) > 0, so the root is bracketed."""
    if k == 0.0:
        return 7.0 / 9.0
    lo, hi = 1e-12, 1.0 - 1e-12
    flo = eq27_residual(lo, k)
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        fm = eq27_residual(mid, k)
        if flo * fm <= 0.0:
            hi = mid
        else:
            lo, flo = mid, fm
    return 0.5 * (lo + hi)


def clf(k):
    """Peak load-factor coefficient at kappa (eq 25)."""
    u = velocity_ratio(k)
    return (2 * u * (u + k) ** 2 / (3 * u + 2 * k)) * \
           ((7 * u + 6 * k) / (2 * u)) ** (1.0 / 3.0)


def grid():
    """Log-spaced kappa grid over the practical range (denser at low kappa)."""
    lo, hi = math.log(KAPPA_MIN), math.log(KAPPA_MAX)
    ks = [math.exp(lo + (hi - lo) * i / (N_POINTS - 1)) for i in range(N_POINTS)]
    return ks, [clf(k) for k in ks]


def max_interp_error(ks, vs):
    """Worst linear-interp error vs the true curve, sampled at segment midpoints."""
    worst = 0.0
    for i in range(len(ks) - 1):
        km = 0.5 * (ks[i] + ks[i + 1])
        lin = vs[i] + (vs[i + 1] - vs[i]) * (km - ks[i]) / (ks[i + 1] - ks[i])
        worst = max(worst, abs(lin - clf(km)))
    return worst


def check():
    u0, c0 = velocity_ratio(0.0), clf(0.0)
    ok_anchor = abs(c0 - ANCHOR_CLF) < 5e-4 and abs(u0 - 7.0 / 9.0) < 1e-9
    ks, vs = grid()
    mono = all(vs[i + 1] > vs[i] for i in range(len(vs) - 1))
    err = max_interp_error(ks, vs)
    print(f"Clf(0) = {c0:.4f} (expect {ANCHOR_CLF}); u(0) = {u0:.5f} (expect {7/9:.5f})")
    print(f"anchor PASS: {ok_anchor}")
    print(f"grid: {len(ks)} pts over kappa in [{KAPPA_MIN}, {KAPPA_MAX}], "
          f"Clf in [{vs[0]:.4f}, {vs[-1]:.4f}], monotone-increasing: {mono}")
    print(f"max linear-interp error (midpoint sample): {err:.2e}")
    return ok_anchor and mono


def fmt(xs):
    return ",\n    ".join(
        ", ".join(f"{x:.8f}" for x in xs[i:i + 6]) for i in range(0, len(xs), 6))


def emit():
    ks, vs = grid()
    body = f"""#pragma once
// AUTO-GENERATED by scripts/precompute_impact_clf.py -- DO NOT EDIT BY HAND.
//
// Hydrodynamic peak load-factor coefficient Clf(kappa) from NACA TN 1516
// (Milwitzky 1948), eqs 25/27. Clf maps the contact state to the peak CG load
// factor:  n_peak = Clf(kappa) * ydot0^2 * (alpha_hull/(W g^2))^(1/3).
//
// NOTE: Clf is the LOAD-factor coefficient (C_l, subscript l = load), NOT the
// aerodynamic max-lift coefficient CLmax (C_L) used by the descent barrier.
//
// Anchor (eqs 39/40): Clf(0) = {ANCHOR_CLF} at u = 7/9 (verified by the script).
// kappa grid is ascending over the practical range [{KAPPA_MIN}, {KAPPA_MAX}];
// the runtime clfLookup() does linear-in-kappa interpolation and clamps outside.
namespace autoland {{

inline constexpr int kImpactClfN = {len(ks)};

inline constexpr double kImpactClfKappa[kImpactClfN] = {{
    {fmt(ks)}
}};

inline constexpr double kImpactClfVal[kImpactClfN] = {{
    {fmt(vs)}
}};

}}  // namespace autoland
"""
    with open(HEADER, "w") as f:
        f.write(body)
    print(f"wrote {os.path.relpath(HEADER)}")


if __name__ == "__main__":
    ok = check()
    if not ok:
        print("ERROR: anchor/monotonicity check failed", file=sys.stderr)
        sys.exit(1)
    if "--check" not in sys.argv:
        emit()
